### ISSUE TITLE
Marina TODO list

### ISSUE THREAD

**Issue by mmarinated** [mmarinated/topic-modeling#4]
# write something here
- [ ] load model from state dict: load options dict, so not to define it all the time.
- [ ] standardize code for data preprocessing for different languages. 
   - [ ] (might want to specify len of train, val. Divide to train,val, save test.)
- [ ] clean code for models.
- [ ] ADD model files to Google Drive. Currently they are on prince.

# Metrics
- [ ] add plots to visualize table
- [ ] report both mean and stderr
- [ ] validate separately on each language and report 3 scores.
